# unstable_features = true

max_width = 80
# format_strings = true
# imports_layout = "HorizontalVertical"
# indent_style = "Visual"
# match_arm_blocks = false
# match_block_trailing_comma = true
# imports_granularity = "Module"
# overflow_delimited_expr = true
# group_imports = "StdExternalCrate"
# space_before_fn_sig_paren = true
# struct_field_align_threshold = 10
# struct_lit_single_line = true
use_field_init_shorthand = true
# wrap_comments = true
